#EMPLOYEE REPORT 
name=input("employee name : ")
empid=int(input("employee id : "))
bs=int(input("basic salary : "))
hra=float(input("hra : "))
da=float(input("da : "))
ta=float(input("ta : "))
pf=float(input("pf : "))
tot= bs+((bs*hra)/100)+((bs*ta)/100)+((bs*da)/100)
gsal=tot-((bs*pf)/100)
print(name)
print(empid)
print(bs)
print(tot)
print(gsal)